#+TITLE: Fosshost CIC Operational Policy Statement
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-bigblow.setup

#+BEGIN_QUOTE
Copyright © 2021 Fosshost CIC and [[https://docs.fosshost.org/en/home/team][contributors]]

Fosshost C.I.C. is a Community Interest Company, registered in England and Wales. Company Reg No: 13356530. Registered Office Address: 7 Bell Yard, London, England, WC2A 2JR, Great Britain.

LICENSE: TBD
#+END_QUOTE

* OUR POLICY

  These are the policies (Our Policy, Our Policies, policy, etc.) of
  Fosshost CIC ("Fosshost", "we", "our", "our volunteers", "our
  directors", "our agents and assignees", etc.).

  Notwithstanding our articles as filed with the office of the
  regulator of the UK CIC, which our policy must be consistent with
  and subject/secondary to, these and no other documents govern our
  organization including our members, agents, and/or assignees when
  acting on our behalf expect whereas our policies (this document or
  documents) make expressly and specifically describe and allow.

** Our Expectations Evolution Policy

#+BEGIN_QUOTE
A practice to properly police Fosshost's polices.
#+END_QUOTE

*** SUMMARY
The ITEMS following create a basis for directors to create and update policy, for other volunteers to raise concerns ("object") to policy, and requires all policy to be consistent with our articles which are superior to our polices.

NOTE: this is just a summary, refer to the ITEMS below for binding policy language.

*** ITEMS
1. Directors shall write policy as needed, and
2. Absent an prior or conflicting policy that policy is immediately in effect, where
3. Policy once effective is binding to/for all our agents and assignees including but not limited to all of our volunteers including our directors.
4. When we replace/amend our policies including this one, and given due notification (e.g, by electronic mail) of all of the directors, this policy and any other of our policies are effective once acknowledged and consented to by one or more other director such that two of our directors have considered the changes,
5. Unless a director shall object (e.g. by comment, verbally, or by other means) in a timely manner, and then
6. Once objected to, policy is effective when consented to a by duly recorded majority representing a quorum of directors.
7. Directors shall raise at their first opportunity objection on behalf of our other volunteers when each shall perceive a consensus or significant majority of affected parties under their supervision have voiced their concerns in good faith concern and given the director shall find such concern may have merit, however
8. Directors are not otherwise obligated to represent or act on behalf of others (for example, of any other of our volunteers) and shall act on their own best knowledge and belief when drafting and reviewing policy, and always that
9. Directors and all other of our volunteers shall always act to the greatest extent they are able within the confines of this and other Fosshost policy, and
10. We shall each use our best judgment striving for prudence and consistency, for example when our policies may appear to conflict, and that
11. At all times we each shall conduct ourselves within our understood legal and ethical confines, such as of applicable law and regulation, and that
12. Each of us shall take it upon ourselves to certify notification to all of our directors any the event they in good faith believe doubt the legally binding nature of this or any Fosshost policy or when they in good faith believe a director or other volunteer may have violated any Fosshost policy,
13. And the secretary shall acknowledge and record any such change, objection, and notification made under this policy and produce such records as needed to conduct our business and upon duly verified request from any and all such entity may have the legal right to make such a demand upon Fosshost, for example the government of the United Kingdom in the course of verifying or investigating our records as permitted and allowed for under UK law,
14. And any and all such which actions required and allowed by our policies as specifically called out, for example for a particular officer or volunteer may be otherwise assigned or delegated as otherwise consistent with Fosshost policies, for example the Secretary may delegate and share information (for example, with other volunteers) as may be necessary, expedient, and consistent with our policies, in order to make, keep, and produce records,
15. And where our policies, of which this forms a part, are not to conflict with our articles,
16. And where in conflict, our articles are considered before and superior to our policies including this one,
17. Except as may relate to amending our articles and related process, where our articles may for a period of not more than three months ("one quarter", usually around 90days) have superseded our articles given they contain such changes as can and do affect our our articles and/or he process by which we have agreed to revise our articles, whereas this may allow us time needed to review and record such changes and to file those changes with external entities such as the UK CIC.

*** TODO
**** DONE relate to articles, cannot superseed save for process for amended
     CLOSED: [2021-04-28 Wed 01:04]
** Our Values and Ethics Policy
#+BEGIN_QUOTE
A statement of our values and accountability.
#+END_QUOTE
*** SUMMARY
The ITEMS following create a basis for a guarantee of good faith in the public interest by stating our values and framework for accountability.  To that end, the language in this section should be simple and unembellished.

NOTE: this is just a summary, refer to the ITEMS below for binding policy language.
*** ITEMS
    1. We seek at all times to earn and to be worthy of trust, and
    2. seek to be respectfully transparent, and
    3. seek to be appropriately discreet, and
    4. seek to communicate faithfully, and
    5. seek to pursue our duties with all due diligence.
    6. We will at all times be honest, and
    7. we will comply with our polices,
    8. we will share and explain our work freely, and
    9. we will prefer, promote, and model the best ideals of the Free
       and Open Source software communities we host and/or endorse, and
    10. we will show our same values to all people and communities.

** Our Community Policy
#+BEGIN_QUOTE
A somewhat intense statement of our specific mission in serving the general interest.
#+END_QUOTE
*** SUMMARY
The ITEMS following align our policy to our mission ("We're on a mission
to empower and support every free and open-source software project. To
go further, together. Our work never stops.").

To that end, this section provides working definitions for certain
"terms of art" (words or phrases, often with synonyms that may appear
interchangeably with the original term throughout our policy, and
which may take on additional or unconventional meaning within the
context of our operations or which we may for other reasons clarify)
and that help to identify and distinguish the interests we serve.

NOTE: this is just a summary, refer to the ITEMS below for binding policy language.
*** ITEMS
    1. FOSS ("FLOSS", "Free Software", "Open Source Software" "Open Source", "Free and Open Source Software")
       1. will usually refer to a product or a combination of products ("program"), and
	  1. includes the program source and other materials in any form or forms ("sources and binaries"), and
	     1. being duly described ("documented"), and
	     2. authored, edited, and/or created ("authored", "maintained"), and
	     3. compiled, built, tested, and distributed ("packaged", "released"), and
	     4. used ("used", "tested", "developed"), and
		1. each of these given above apply ("complete program"), or
		2. or when one or more of these above ("developed and/or used", etc.) apply, and
	     5. one or more such program once installed (e.g. service, job, instance, virtual machine, or client),
		1. Such that the program runs or will run ("run", "executed"), and
		   1. Such that one or more
		   2. servers, desktop and/or laptop computers, mobile devices such as smart phones ("machine"), or
		   3. such simulated by electronic means ("virtual machine"), or
		2. such that a program, service, or capability becomes available ("FOSSaaS"), or
		3. such that a task is performed or will be performed ("FOSS Script"), or
		4. a physical or simulated physical computing device providing such ("FOSS device"), or
	     6. any other mechanical or other device that can run the program ("FOSS machine"),
	  2. Or otherwise causing a program or code for a program to be
	     1. developed ("FOSS creation"), or
	     2. executed ("FOSS use"),
	  3. But only when developed and/or used under and per the terms of a license ("FOSS program")
	     1. [[https://www.gnu.org/licenses/license-list.en.html][endorsed or approved]] by the Free Software Foundation ("FSF"), or
	     2. meeting [[https://opensource.org/osd][Open Source Definition]] (ODS) criteria of the Open Source Initiative ("OSI"),
       2. But may also refer
	  1. To a specific person, or specific persons, or specific group of persons ("community"), who
	     1. voluntary develops a specific FOSS program or programs ("FOSS developer", "FOSS project", "project"), or
	     2. Uses and promotes the use of a FOSS program ("FOSS user"), or
	  2. To a group of such person ("FOSS user group", "FOSS user community"), or
	  3. To any other person or community who in and from good standing and in good faith ("well regarded) does
	     1. meaningfully and demonstrably support FOSS project or projects ("FOSS supporter"), and
		1. regularly organizes support for FOSS projects ("FOSS Community Interest Organization"), or
		2. by other conduct, communication or other specific and recognized act ("support"), does
	     2. further FOSS development ("FOSS community member"), or
	     3. does more than more than one of these ("FOSS Community").
    2. FOSS Hosting and Service
       1. Our purpose and function ("mission") is to provide this, meaning
       2. our records as a registered and accountable organization ("records", "Fosshost records"),
       3. shall relate to that business, and including
	  1. internal accounting and reporting, and
	  2. such external accounting as we are duly required to produce, and
       4. shall relate that business to our practices as a FOSS Community Interest Organization, and that
       5. Fosshost shall in all policies ("comprehensively"), and
	  1. Other regular and authorized procedures ("procedures"),
	  2. and organizational practice ("tradition"),
       6. keep such records as are or may be vital ("vital records"), and
       7. to establish and retain within Fosshost records ("keep")
	  1. such information as may be needed to account, track, measure or otherwise calculate
	  2. our assets, and
	  3. our liabilities, and
	  4. our affect on our community, and
	  5. our understanding of and respect for FOSS, and to
       8. relate such information to our mission as best we can, and to
       9. periodically and as necessary review comprehensively ("audit", "self audit"), and
       10. consider the results of such audits as vital records, and
       11. and including as vital records any and all records showing specific and unacceptable ("malfeasance"),
	   1. action taken by Fosshost ("impropriety"), and
	   2. action taken our behalf and with our general knowledge and consent ("collusion"),
       12. and to include as vital such records substantiating malfeasance as we can find, including
	   1. detailed instructions related to the performance of the audit, and
	   2. the results of the audit including actions taken in consequence, and
	      1. in cases where malfeasance has
		 1. been found, or
		 2. is suspected to have occured, and
	      2. including any and all access records and logs and other technical work-product, and
	      3. receipts, invoices, and internal and external communications we might not otherwise share, and
	      4. that may constituent or corroborate the audit which has found malfeasance, and to
       13. bring that information forward ("notification of malfeasance") to
	   1. the FOSS community, and
	   2. the general public, and,
	   3. appropriate regulatory bodies or agencies, and
	   4. any other public body, such as
	      1. applicable law enforcement,
	      2. where and as may be prudent and advisable.

** Our Teamwork Policy
** Our Sponsorship and Contribution Policy
** Our Deliberation and Record Keeping ("Privacy") Policy
** Our Continuation and Termination of Authority Policy
