#+TITLE: Policy for Twitter
#+AUTHOR: Bruno Miguel
#+EMAIL: bruno@fosshost.org
#+LANGUAGE: en
#+OPTIONS: H:6 num:t toc:6 p:t

* Policy for Twitter
  :PROPERTIES:
  :CUSTOM_ID: tweeting-policyframework
  :END:
At Twitter, we have two official accounts: [[https://twitter.com/fosshostorg][@fosshostorg]] and [[https://twitter.com/aarch64org][@aarch64org]]. We're on this social network to let people know what we're doing as a project, and also - but not limited - to:

- interact with other accounts to raise awareness, on the media or other communities, about our projects;
- allow the outside world to contact us;
- answer questions that don't need to be answered in different communication channels (ex: how do I apply?);
- announce issues with the services that fulfil the requirements needed to be tweeted.

Both accounts should reflect our core values and principles, and be warm and welcoming, as it is part of our identity in the quest to help the entire FOSS community.

We are a project run by people who volunteer their free time to help Fosshost and the FOSS community. This should also be reflected in the way we communicate on Twitter. Keep in mind that when you post a message, big or small, you are representing Fosshost to a global audience, and you need to respect it all the time.

** Rules for communicating on Twitter
   :PROPERTIES:
   :CUSTOM_ID: rules-for-communicating-on-twitter
   :END:
*** The do's
    :PROPERTIES:
    :CUSTOM_ID: the-dos
    :END:

- Be friendly and welcoming;
- Treat others with respect;
- Positively amplify our work and contributions;
- Positively amplify the work and contributions of our tenants;
- Promote a positive, fun, and productive discourse and presence online;
- Ask the team for advice if you're not comfortable or confident posting something;
- Amplify the voice of community members, users and contributors alike if it's related to FOSS.

*** The don'ts
    :PROPERTIES:
    :CUSTOM_ID: the-donts
    :END:

- Don't feed the trolls;
- Don't be rude;
- Don't insult;
- Don't argue;
- Avoid bashing brands, companies, individuals, or other projects;
- Respond to mentions on Twitter promptly (whenever possible) with quality engagement;
- Avoid speculation;
- Don't share any personal/confidential information, including any information shared with you in confidence or within private channels;
- Don't post anything on social media you wouldn't want to see reported on news sites.

*** Tone
    :PROPERTIES:
    :CUSTOM_ID: tone
    :END:
Our tone should be friendly, positive, fun, authentic, aspirational and slightly tongue-in-cheek.

A volunteer tweeting can also add a bit of their identity to a tweet, so it doesn't stray from our rules. For example, we don't want someone sending the application's link with a rolling eyes emoji.

** Who should have access to the Twitter accounts
   :PROPERTIES:
   :CUSTOM_ID: who-should-have-access-to-the-twitter-accounts
   :END:
Access to the Twitter account should be as restrictive as possible so that possible issues are minimized. That said, four types of internal roles should always have access:
- Directors;
- Executive Officers (CEO, COO, CTO and deputies);
- Head of marketing;
- Communication team

** Examples of tweets
   :PROPERTIES:
   :CUSTOM_ID: examples-of-tweets
   :END:
*** Issues with the service
    :PROPERTIES:
    :CUSTOM_ID: issues-with-the-service
    :END:

Assume we have a node down due to a hardware failure, and the company where the node is hosted gives an ETA of one hour. The tweet can be like the following example:

#+begin_quote
Our x86 NQTHV0 node is down due to a hard drive failure. We're working as fast as possible to get it fixed and hope to have the node back up in 1h. We apologize for any inconvenience this may cause you.
#+end_quote

Now assume we have connectivity issues and no ETA:

#+begin_quote
Our x86 NQTHV0 is experiencing connectivity issues. We're on it and will have it fixed as fast as possible. Apologies for the inconvenience this is causing you.
#+end_quote

We could also have a scheduled maintenance:

#+begin_quote
On the 10th of December, at 10AM PST, our NQTHV0 will undergo maintenance. We anticipate 30 minutes of downtime.
#+end_quote

If the downtime was longer than previously anticipated for the maintenance:

#+begin_quote
Sorry, folks, the maintenance is taking a little bit longer than anticipated. Rest assured, we are working hard to conclude it as quickly as possible.
#+end_quote

** Tweeting about tenants
   :PROPERTIES:
   :CUSTOM_ID: tweeting-about-tenants
   :END:
From time to time, we should shout out to a tenant of ours, no matter the size of the project. We could - and should - even congratulate a tenant for a new release or a new achievement.

Doing so help us by showing we recognize and appreciate our tenants, and it also helps us build a good relationship with them.

*** Example of tweets
    :PROPERTIES:
    :CUSTOM_ID: example-of-tweets
    :END:
Suppose a tenant releases a new version:

#+begin_quote
  Congratulations on the new release, @ubuntu_unity
#+end_quote

#+begin_quote
  Another solid release by @garudalinux
#+end_quote

Or suppose a tenant gets an important milestone:

#+begin_quote
  Keep up the good work, @Serpent_OS
#+end_quote

/Policy partially inspired on
[[https://github.com/bsdlabs/community/blob/main/guidelines.md][BSDLabs
guidelines]] and
[[https://www.apache.org/foundation/marks/socialmedia][Apache
guidelines]]/
